services:
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=Yamini27
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shelter
    volumes:
      - db_data:/var/lib/postgresql/db_data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    #networks:
     # - postgres1

  etl:
    build: .
    command: https://raw.githubusercontent.com/PriyankaKandikattu/Datacenterscalecomputing_HW/HW2/Austin_Animal_Center_Outcomes_20231017.csv
    depends_on:
      - db
             

volumes:
  db_data:

#networks:
  #postgres1:
   # driver: bridge


    